### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by tsani** [labcoders/screen-addon#2]
- [ ] Figure out how to set pins from assembly
- [ ] Figure out how to compile assembly and upload it
- [ ] Figure out how many cycles we need to read a byte from the buffer and bang it
- [ ] Compute how many pixels we can draw at 30Hz refresh rate given that number of cycles

**Comment by tsani** [comment]
This stuff is pretty much moot since @kevin-li-195 discovered how to very quickly set the pins from C using the `PORT{A,B,C}` variables.
